import type { Metadata } from "next";
import { Cairo } from "next/font/google";
import "./globals.css";
import ProvdierApp from "@/context/appContext";
import { Toaster } from "react-hot-toast";
import { cookies } from "next/headers";
import { fetchData } from "@/lib/fetchData";

const cairo = Cairo({
  subsets: ['latin'],
});
export const metadata: Metadata = {
  title: "Mostasmer payment",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const token = await (await cookies()).get('token')?.value;
  const { data } = await fetchData('/api/verify-me', {
    headers: {
      Authorization: `Bearer ${token}`,
    }
  })

  return (
    <html lang="en">
      <body
        className={`${cairo.className} antialiased`}
      >
        <ProvdierApp
          user={data?.user}
          token={token as string}
        >
          {children}
        </ProvdierApp>
        <Toaster toastOptions={{ duration: 4000, position: 'bottom-left' }} />
      </body>
    </html>
  );
}
